services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "5050:5050"
        environment:
            - NODE_ENV=production
        restart: always
